Config = {}

-- Menu --
Config.Header = "Boosting Contracts"
Config.HeaderIcon = "fas fa-file-signature"
Config.MenuIcon = "fas fa-car"

-- Messages --
Config.DropMessage = "Vehicle successfully dropped off" -- Vehicle Dropoff Message

-- Zones --
Config.ZoneRadius = 50

Config.VehicleSpawnLocations = {
    vector3(923.56, -1522.35, 29.27), 
    vector3(133.3, -2490.71, 4.23),
    vector3(-334.89, -945.29, 29.31)
}

Config.DropOffLocations = {
    vector3(-1597.45, -1003.42, 5.85),
    vector3(364.17, 270.34, 101.38),
    vector3(-465.79, -1719.47, 16.89)
}

-- Hack --
Config.HackTime = 20000
Config.Keys = 5

-- Contracts --
Config.RandomContractAmount = 3

Config.Contracts = {
    {
        class = "D",
        type = "Dropoff",
        vehicle = "blista",
        plate = "Boosting",
        reward = 500,
    },
    {
        class = "D",
        type = "Dropoff",
        vehicle = "panto",
        plate = "Boosting1",
        reward = 500,
    },
    {
        class = "C",
        type = "Dropoff",
        vehicle = "seminole2",
        plate = "Boosting2",
        reward = 1000,
    },
    {
        class = "C",
        type = "Dropoff",
        vehicle = "washigton",
        plate = "Boosting3",
        reward = 1000,
    },
    {
        class = "B",
        type = "Dropoff",
        vehicle = "stratum",
        plate = "Boosting4",
        reward = 1500,
    },
    {
        class = "B",
        type = "Dropoff",
        vehicle = "jackal",
        plate = "Boosting5",
        reward = 1500,
    },
    {
        class = "A",
        type = "Dropoff",
        vehicle = "schwarzer",
        plate = "Boosting6",
        reward = 2000,
    },
    {
        class = "A",
        type = "Dropoff",
        vehicle = "Penumbra2",
        plate = "Boosting7",
        reward = 2000,
    }
}

Config.Colors = {
    [0] = "Black",
    [1] = "Graphite",
    [2] = "Black Steel",
    [3] = "Dark Steel",
    [4] = "Silver",
    [5] = "Bluish Silver",
    [6] = "Rolled Steel",
    [7] = "Shadow Silver",
    [8] = "Stone Silver",
    [9] = "Midnight Silver",
    [10] = "Cast Iron Silver",
    [11] = "Red",
    [12] = "Torino Red",
    [13] = "Formula Red",
    [14] = "Lava Red",
    [15] = "Blaze Red",
    [16] = "Grace Red",
    [17] = "Garnet Red",
    [18] = "Sunset Red",
    [19] = "Cabernet Red",
    [20] = "Wine Red",
    [21] = "Candy Red",
    [22] = "Hot Pink",
    [23] = "Pfsiter Pink",
    [24] = "Salmon Pink",
    [25] = "Sunrise Orange",
    [26] = "Orange",
    [27] = "Bright Orange",
    [28] = "Gold",
    [29] = "Bronze",
    [30] = "Yellow",
    [31] = "Race Yellow",
    [32] = "Dew Yellow",
    [33] = "Dark Green",
    [34] = "Racing Green",
    [35] = "Sea Green",
    [36] = "Olive Green",
    [37] = "Bright Green",
    [38] = "Gasoline Green",
    [39] = "Lime Green",
    [40] = "Midnight Blue",
    [41] = "Galaxy Blue",
    [42] = "Dark Blue",
    [43] = "Saxon Blue",
    [44] = "Blue",
    [45] = "Mariner Blue",
    [46] = "Harbor Blue",
    [47] = "Diamond Blue",
    [48] = "Surf Blue",
    [49] = "Nautical Blue",
    [50] = "Ultra Blue",
    [51] = "Schafter Purple",
    [52] = "Spinnaker Purple",
    [53] = "Midnight Purple",
    [54] = "Bright Purple",
    [55] = "Cream",
    [56] = "Ice White",
    [57] = "Frost White",
    [58] = "Brown",
    [59] = "Bison Brown",
    [60] = "Creeen Brown",
    [61] = "Feltzer Brown",
    [62] = "Maple Brown",
    [63] = "Beechwood Brown",
    [64] = "Sienna Brown",
    [65] = "Saddle Brown",
    [66] = "Moss Brown",
    [67] = "Woodbeech Brown",
    [68] = "Straw Brown",
    [69] = "Sandy Brown",
    [70] = "Bleached Brown",
    [71] = "Util Black",
    [72] = "Util Black Poly",
    [73] = "Util Dark Silver",
    [74] = "Util Silver",
    [75] = "Util Gun Metal",
    [76] = "Util Shadow Silver",
    [77] = "Worn Black",
    [78] = "Worn Graphite",
    [79] = "Worn Silver Grey",
    [80] = "Worn Silver",
    [81] = "Worn Blue Silver",
    [82] = "Worn Shadow Silver",
    [83] = "Worn Red",
    [84] = "Worn Golden Red",
    [85] = "Worn Dark Red",
    [86] = "Worn Orange",
    [87] = "Worn Light Orange",
    [88] = "Worn Taxi Yellow",
    [89] = "Worn Police Car Blue",
    [90] = "Worn Green",
    [91] = "Worn Sea Wash",
    [92] = "Worn Dark Blue",
    [93] = "Worn Blue",
    [94] = "Worn Light Blue",
    [95] = "Worn Honey Beige",
    [96] = "Worn Brown",
    [97] = "Worn Dark Brown",
    [98] = "Worn Straw Beige",
    [99] = "Brushed Steel",
    [100] = "Brushed Black Steel",
    [101] = "Brushed Aluminium",
    [102] = "Chrome",
    [103] = "Worn Off White",
    [104] = "Util Off White",
    [105] = "Worn Orange",
    [106] = "Worn Light Orange",
    [107] = "Metallic Securicor Green",
    [108] = "Worn Taxi Yellow",
    [109] = "Police Car Blue",
    [110] = "Matte Green",
    [111] = "Matte Brown",
    [112] = "Worn Orange",
    [113] = "Matte White",
    [114] = "Worn White",
    [115] = "Worn Olive Army Green",
    [116] = "Pure White",
    [117] = "Hot Pink",
    [118] = "Salmon Pink",
    [119] = "Pfister Pink",
    [120] = "Bright Orange",
    [121] = "Green",
    [122] = "Blue",
    [123] = "Mighty Orange",
    [124] = "Pigeon Blue",
    [125] = "Gasoline Blue Green",
    [126] = "Purple",
    [127] = "Spinnaker Purple",
    [128] = "Metallic Lava Red",
    [129] = "Chrome",
    [130] = "Worn Off White",
    [131] = "Util Off White",
    [132] = "Worn Orange",
    [133] = "Worn Light Orange",
    [134] = "Metallic Securicor Green",
    [135] = "Worn Taxi Yellow",
    [136] = "Police Car Blue",
    [137] = "Matte Green",
    [138] = "Matte Brown",
    [139] = "Worn Orange",
    [140] = "Matte White",
    [141] = "Worn White",
    [142] = "Worn Olive Army Green",
    [143] = "Pure White",
    [144] = "Hot Pink",
    [145] = "Salmon Pink",
    [146] = "Pfister Pink",
    [147] = "Bright Orange",
    [148] = "Green",
    [149] = "Blue",
    [150] = "Mighty Orange",
    [151] = "Pigeon Blue",
    [152] = "Gasoline Blue Green",
    [153] = "Purple",
    [154] = "Spinnaker Purple",
    [155] = "Metallic Lava Red",
}    